title: null
email: aaronrbg@gmail.com
author:
  name: Aaron Rosenberg
  email: aaronrbg@gmail.com
  website: https://mountainlife.tech
description: >- # this means to ignore newlines until "baseurl:"
  Final Fest 7
url: "https://mountainlife.tech/"
